version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      playwright:
        patterns:
          - playwright

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
